delete from tblbackup;

ALTER SEQUENCE tblbackup_backup_id_seq RESTART WITH 1;

insert into tblbackup (backup_date, backup_file, user_id) values ('8/26/2022', 'vel', 88);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/4/2022', 'aliquam', 95);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/5/2022', 'in faucibus', 75);
insert into tblbackup (backup_date, backup_file, user_id) values ('2/3/2022', 'nam', 3);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/2/2022', 'mi', 77);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/29/2022', 'pede', 9);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/10/2022', 'congue', 4);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/23/2022', 'sociis natoque', 36);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/16/2021', 'tincidunt', 44);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/17/2022', 'odio', 53);
insert into tblbackup (backup_date, backup_file, user_id) values ('9/6/2022', 'non mattis', 5);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/22/2022', 'nulla', 61);
insert into tblbackup (backup_date, backup_file, user_id) values ('2/1/2022', 'tortor', 64);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/3/2022', 'quam', 77);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/31/2022', 'amet lobortis', 99);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/17/2022', 'ultrices posuere', 13);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/6/2022', 'mi nulla', 81);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/11/2021', 'nec molestie', 23);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/12/2022', 'vestibulum', 95);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/3/2022', 'ipsum dolor', 58);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/25/2022', 'in blandit', 17);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/14/2022', 'in', 45);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/29/2022', 'ligula', 16);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/5/2022', 'a pede', 25);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/6/2022', 'accumsan tellus', 100);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/8/2022', 'enim', 9);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/15/2022', 'nec', 54);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/29/2022', 'vivamus', 30);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/30/2022', 'at', 61);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/19/2021', 'consequat', 92);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/9/2022', 'odio porttitor', 25);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/16/2022', 'luctus', 20);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/17/2022', 'habitasse', 78);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/24/2022', 'tristique est', 53);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/24/2022', 'venenatis tristique', 1);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/2/2022', 'augue', 78);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/17/2022', 'sem duis', 18);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/5/2022', 'rutrum', 9);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/9/2022', 'rutrum ac', 95);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/9/2022', 'vitae nisi', 35);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/14/2022', 'aliquam', 90);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/9/2022', 'at', 99);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/12/2022', 'amet nunc', 37);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/10/2022', 'orci luctus', 75);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/10/2022', 'cubilia curae', 25);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/1/2022', 'erat', 94);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/17/2022', 'ut erat', 86);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/31/2022', 'in imperdiet', 19);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/24/2022', 'tempus', 98);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/13/2022', 'felis sed', 17);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/23/2022', 'dapibus at', 67);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/26/2022', 'at', 41);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/25/2022', 'sem praesent', 1);
insert into tblbackup (backup_date, backup_file, user_id) values ('9/6/2022', 'parturient montes', 85);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/17/2022', 'potenti in', 76);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/3/2021', 'tincidunt eu', 28);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/31/2022', 'in', 50);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/14/2022', 'nonummy', 77);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/23/2022', 'orci luctus', 2);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/14/2022', 'diam vitae', 17);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/16/2022', 'varius nulla', 20);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/15/2022', 'eu massa', 5);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/21/2021', 'justo etiam', 20);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/19/2022', 'adipiscing lorem', 80);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/23/2022', 'metus sapien', 22);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/4/2022', 'donec', 67);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/11/2022', 'non interdum', 89);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/4/2022', 'mi', 63);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/31/2021', 'in', 58);
insert into tblbackup (backup_date, backup_file, user_id) values ('10/1/2022', 'potenti nullam', 63);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/6/2022', 'ultrices', 52);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/7/2022', 'consequat metus', 49);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/15/2022', 'ante ipsum', 73);
insert into tblbackup (backup_date, backup_file, user_id) values ('5/9/2022', 'sapien quis', 20);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/13/2022', 'vel sem', 43);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/15/2022', 'at', 99);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/24/2022', 'nulla nisl', 70);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/9/2022', 'leo', 75);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/5/2022', 'quis justo', 72);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/5/2022', 'non lectus', 64);
insert into tblbackup (backup_date, backup_file, user_id) values ('2/13/2022', 'nulla suscipit', 71);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/16/2022', 'justo', 87);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/18/2022', 'molestie hendrerit', 84);
insert into tblbackup (backup_date, backup_file, user_id) values ('2/21/2022', 'blandit', 2);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/1/2021', 'platea dictumst', 60);
insert into tblbackup (backup_date, backup_file, user_id) values ('7/21/2022', 'aliquet', 31);
insert into tblbackup (backup_date, backup_file, user_id) values ('1/1/2022', 'ut odio', 32);
insert into tblbackup (backup_date, backup_file, user_id) values ('12/20/2021', 'mauris enim', 93);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/17/2022', 'aliquet pulvinar', 94);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/13/2022', 'nisl', 81);
insert into tblbackup (backup_date, backup_file, user_id) values ('11/28/2022', 'dolor morbi', 76);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/10/2022', 'accumsan tellus', 36);
insert into tblbackup (backup_date, backup_file, user_id) values ('9/22/2022', 'dapibus', 81);
insert into tblbackup (backup_date, backup_file, user_id) values ('9/19/2022', 'convallis', 20);
insert into tblbackup (backup_date, backup_file, user_id) values ('8/8/2022', 'vel', 11);
insert into tblbackup (backup_date, backup_file, user_id) values ('2/27/2022', 'in', 92);
insert into tblbackup (backup_date, backup_file, user_id) values ('3/28/2022', 'penatibus', 47);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/24/2022', 'phasellus id', 60);
insert into tblbackup (backup_date, backup_file, user_id) values ('6/14/2022', 'nisl', 40);
insert into tblbackup (backup_date, backup_file, user_id) values ('4/15/2022', 'vel', 86);