delete from tblcomment;

ALTER SEQUENCE tblcomment_comment_id_seq RESTART WITH 1;

insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('duis faucibus accumsan odio curabitur', 8, 92, '4/15/2022', true, 51);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vel sem sed sagittis nam congue risus semper porta', 76, 55, '10/7/2022', true, 73);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sit amet diam in magna bibendum imperdiet nullam orci', 86, 92, '4/9/2022', false, 13);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('dolor vel est donec odio justo', 62, 48, '6/8/2022', true, 9);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('parturient montes nascetur ridiculus mus', 27, 8, '8/20/2022', true, 47);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 74, 78, '11/2/2022', true, 16);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 18, 87, '3/20/2022', true, 90);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tincidunt eu felis fusce posuere', 43, 1, '5/6/2022', true, 58);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('duis bibendum felis sed interdum venenatis turpis enim blandit', 46, 85, '2/11/2022', true, 81);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tellus nisi eu orci mauris lacinia sapien quis', 41, 49, '12/30/2021', false, 4);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('a suscipit nulla elit ac', 12, 92, '5/21/2022', true, 84);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('et eros vestibulum ac est lacinia nisi venenatis tristique', 24, 51, '4/7/2022', false, 41);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('convallis nunc proin at turpis', 81, 31, '2/15/2022', true, 61);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('turpis a pede posuere nonummy', 51, 38, '11/18/2022', false, 33);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 62, 31, '10/11/2022', true, 64);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sollicitudin mi sit amet lobortis sapien sapien non mi', 24, 64, '1/11/2022', false, 43);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('potenti in eleifend quam a odio in hac habitasse platea', 57, 67, '2/6/2022', false, 96);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vestibulum sagittis sapien cum sociis natoque', 79, 2, '7/13/2022', false, 42);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('fermentum donec ut mauris eget massa tempor convallis', 39, 31, '12/16/2021', true, 66);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 65, 62, '1/21/2022', true, 62);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 65, 51, '1/2/2022', true, 54);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('est et tempus semper est quam pharetra magna ac', 99, 84, '3/24/2022', true, 10);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('pellentesque quisque porta volutpat erat quisque erat eros', 58, 8, '7/6/2022', true, 81);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('nullam orci pede venenatis non sodales sed tincidunt eu felis', 1, 50, '5/23/2022', true, 59);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ut massa volutpat convallis morbi', 72, 2, '4/19/2022', true, 25);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tincidunt lacus at velit vivamus vel nulla eget eros elementum', 35, 80, '6/15/2022', true, 4);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ultrices posuere cubilia curae donec pharetra', 30, 63, '2/8/2022', true, 85);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('fusce congue diam id ornare', 44, 29, '8/26/2022', false, 34);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('nibh fusce lacus purus aliquet at feugiat non pretium', 57, 15, '11/5/2022', true, 97);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('interdum mauris non ligula pellentesque ultrices phasellus', 17, 36, '4/21/2022', false, 47);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('lobortis vel dapibus at diam nam tristique tortor eu pede', 62, 31, '2/13/2022', false, 57);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('praesent lectus vestibulum quam sapien varius ut blandit non', 35, 87, '2/23/2022', true, 25);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('egestas metus aenean fermentum donec ut mauris eget', 9, 58, '2/28/2022', true, 2);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('in congue etiam justo etiam pretium iaculis justo in', 23, 80, '8/4/2022', false, 94);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('lectus in est risus auctor sed tristique in tempus sit', 29, 99, '9/25/2022', false, 47);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ac diam cras pellentesque volutpat dui maecenas tristique est', 79, 2, '2/1/2022', true, 64);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('at velit eu est congue elementum in hac', 10, 72, '8/14/2022', false, 53);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('lorem quisque ut erat curabitur gravida', 85, 17, '2/17/2022', true, 32);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sagittis nam congue risus semper porta volutpat quam pede', 50, 80, '12/13/2021', false, 87);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('quam sollicitudin vitae consectetuer eget rutrum at', 32, 63, '3/14/2022', true, 40);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('varius ut blandit non interdum in ante vestibulum', 65, 23, '8/28/2022', true, 35);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sapien non mi integer ac', 31, 1, '12/8/2021', false, 3);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('aenean fermentum donec ut mauris eget massa tempor', 64, 14, '4/9/2022', true, 38);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('lorem vitae mattis nibh ligula nec', 86, 88, '1/31/2022', false, 86);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('viverra diam vitae quam suspendisse potenti nullam porttitor', 55, 35, '6/10/2022', false, 78);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('nam ultrices libero non mattis pulvinar', 74, 80, '5/22/2022', true, 82);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', 41, 96, '11/25/2022', true, 70);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('in lectus pellentesque at nulla', 13, 99, '6/12/2022', false, 25);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vel accumsan tellus nisi eu', 1, 43, '11/9/2022', false, 79);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('montes nascetur ridiculus mus vivamus', 68, 73, '3/21/2022', false, 93);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('fusce consequat nulla nisl nunc nisl duis bibendum felis', 16, 39, '7/1/2022', false, 85);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('semper sapien a libero nam dui', 33, 17, '11/27/2022', true, 83);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('dui vel sem sed sagittis nam congue', 100, 40, '2/19/2022', false, 57);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('velit donec diam neque vestibulum eget vulputate', 13, 35, '4/10/2022', true, 2);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('erat quisque erat eros viverra eget congue eget', 86, 90, '6/26/2022', true, 18);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tempus vivamus in felis eu sapien', 43, 98, '9/5/2022', true, 64);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('augue vestibulum rutrum rutrum neque aenean', 35, 78, '4/11/2022', true, 92);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 52, 53, '8/1/2022', false, 88);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('erat tortor sollicitudin mi sit', 95, 4, '8/4/2022', false, 72);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('nibh in lectus pellentesque at nulla suspendisse potenti cras in', 19, 34, '12/5/2021', false, 19);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tortor sollicitudin mi sit amet lobortis', 10, 86, '5/12/2022', true, 68);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vestibulum sagittis sapien cum sociis natoque penatibus et', 84, 43, '4/16/2022', true, 1);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('interdum mauris non ligula pellentesque ultrices phasellus id sapien', 52, 22, '4/18/2022', false, 89);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('arcu libero rutrum ac lobortis vel', 79, 42, '11/2/2022', true, 35);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('leo odio condimentum id luctus nec molestie sed justo', 4, 65, '2/19/2022', false, 2);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('amet eleifend pede libero quis orci nullam molestie', 50, 43, '3/17/2022', false, 54);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti', 87, 1, '9/5/2022', false, 28);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sollicitudin mi sit amet lobortis sapien', 44, 96, '3/7/2022', true, 39);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('imperdiet sapien urna pretium nisl ut volutpat sapien arcu', 23, 52, '1/9/2022', true, 53);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('mi sit amet lobortis sapien sapien non mi integer', 39, 78, '3/30/2022', false, 69);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ligula suspendisse ornare consequat lectus in est risus auctor sed', 60, 62, '1/5/2022', false, 11);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ultrices posuere cubilia curae duis faucibus accumsan odio curabitur', 19, 44, '8/17/2022', false, 5);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('amet nulla quisque arcu libero', 95, 14, '5/16/2022', true, 18);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 9, 21, '2/11/2022', true, 42);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('luctus et ultrices posuere cubilia', 6, 76, '8/10/2022', false, 75);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('erat vestibulum sed magna at nunc commodo placerat', 60, 20, '1/27/2022', false, 51);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('quis orci nullam molestie nibh in lectus', 24, 12, '1/3/2022', true, 27);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('arcu libero rutrum ac lobortis vel', 23, 9, '5/10/2022', false, 78);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sapien cursus vestibulum proin eu mi nulla', 55, 9, '10/27/2022', false, 27);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vulputate elementum nullam varius nulla facilisi cras', 22, 37, '10/26/2022', true, 34);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('in lacus curabitur at ipsum ac', 50, 14, '10/11/2022', true, 17);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('bibendum imperdiet nullam orci pede venenatis non sodales sed', 64, 42, '5/7/2022', false, 21);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ligula nec sem duis aliquam convallis nunc proin at', 93, 68, '12/26/2021', true, 87);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('consequat ut nulla sed accumsan', 44, 91, '9/28/2022', true, 54);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('velit vivamus vel nulla eget eros elementum pellentesque', 15, 36, '5/4/2022', true, 16);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('dui maecenas tristique est et tempus semper est quam pharetra', 34, 17, '8/13/2022', false, 37);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sit amet cursus id turpis integer aliquet', 99, 21, '4/27/2022', false, 13);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('vestibulum vestibulum ante ipsum primis', 32, 76, '5/5/2022', true, 77);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('neque sapien placerat ante nulla justo aliquam quis turpis', 11, 9, '5/8/2022', false, 90);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('sit amet sem fusce consequat nulla', 21, 12, '11/17/2022', false, 71);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('accumsan tellus nisi eu orci mauris lacinia sapien', 51, 95, '6/26/2022', false, 66);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tincidunt ante vel ipsum praesent blandit lacinia', 7, 18, '12/31/2021', true, 50);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('dictumst etiam faucibus cursus urna ut tellus', 18, 16, '8/17/2022', true, 30);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('eu orci mauris lacinia sapien quis libero', 61, 43, '7/7/2022', true, 36);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('ultrices enim lorem ipsum dolor sit amet consectetuer', 8, 58, '2/2/2022', false, 74);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('amet nulla quisque arcu libero rutrum', 46, 56, '3/21/2022', false, 73);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('posuere cubilia curae nulla dapibus', 32, 76, '7/31/2022', false, 50);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('turpis sed ante vivamus tortor duis mattis', 36, 48, '10/12/2022', true, 14);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('urna ut tellus nulla ut', 22, 15, '2/24/2022', true, 18);
insert into tblcomment (comment_content, subscriber_id, news_id, comment_date, comment_status, user_id) values ('tincidunt ante vel ipsum praesent blandit lacinia erat', 13, 5, '3/10/2022', false, 32);