delete from tblnewscategory;

ALTER SEQUENCE tblnewscategory_category_id_seq RESTART WITH 1;

insert into tblnewscategory (category_name, category_description) values ('Sports', 'in imperdiet et');
insert into tblnewscategory (category_name, category_description) values ('Science', 'tincidunt lacus at velit');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'ut at dolor quis odio');
insert into tblnewscategory (category_name, category_description) values ('Science', 'diam cras pellentesque');
insert into tblnewscategory (category_name, category_description) values ('Health', 'nulla elit ac nulla sed');
insert into tblnewscategory (category_name, category_description) values ('Family', 'integer ac neque duis');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'congue etiam justo etiam');
insert into tblnewscategory (category_name, category_description) values ('Health', 'iaculis diam erat');
insert into tblnewscategory (category_name, category_description) values ('World', 'vel est donec odio justo');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'tempus vivamus in felis');
insert into tblnewscategory (category_name, category_description) values ('Sports', 'venenatis tristique fusce');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'magna vestibulum aliquet');
insert into tblnewscategory (category_name, category_description) values ('World', 'potenti cras in purus eu');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'in leo maecenas pulvinar');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'dui nec nisi volutpat eleifend');
insert into tblnewscategory (category_name, category_description) values ('World', 'pulvinar nulla pede');
insert into tblnewscategory (category_name, category_description) values ('Science', 'sapien arcu sed augue');
insert into tblnewscategory (category_name, category_description) values ('Family', 'viverra eget congue');
insert into tblnewscategory (category_name, category_description) values ('Family', 'felis eu sapien cursus');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'rhoncus dui vel');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'metus arcu adipiscing molestie hendrerit');
insert into tblnewscategory (category_name, category_description) values ('World', 'elementum pellentesque quisque');
insert into tblnewscategory (category_name, category_description) values ('World', 'viverra eget congue eget semper');
insert into tblnewscategory (category_name, category_description) values ('Health', 'lectus aliquam sit');
insert into tblnewscategory (category_name, category_description) values ('Business', 'vel accumsan tellus nisi eu');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'libero convallis eget eleifend');
insert into tblnewscategory (category_name, category_description) values ('Sports', 'nulla sed accumsan felis');
insert into tblnewscategory (category_name, category_description) values ('Health', 'vitae mattis nibh ligula nec');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'mauris viverra diam vitae quam');
insert into tblnewscategory (category_name, category_description) values ('Video', 'lacinia aenean sit amet');
insert into tblnewscategory (category_name, category_description) values ('Family', 'ultrices posuere cubilia');
insert into tblnewscategory (category_name, category_description) values ('Business', 'blandit non interdum');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'ante vestibulum ante ipsum primis');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'enim sit amet');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'donec odio justo sollicitudin');
insert into tblnewscategory (category_name, category_description) values ('Business', 'eleifend pede libero quis orci');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'posuere cubilia curae duis');
insert into tblnewscategory (category_name, category_description) values ('Family', 'adipiscing elit proin risus praesent');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'integer aliquet massa id');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'mus etiam vel augue vestibulum');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'eleifend luctus ultricies eu nibh');
insert into tblnewscategory (category_name, category_description) values ('Health', 'tellus nisi eu orci mauris');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'justo maecenas rhoncus aliquam');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'neque libero convallis eget eleifend');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'aenean auctor gravida sem');
insert into tblnewscategory (category_name, category_description) values ('World', 'risus dapibus augue vel accumsan');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'nec dui luctus');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'convallis eget eleifend');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'in blandit ultrices enim');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'quis odio consequat');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'semper interdum mauris ullamcorper');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'aliquet massa id lobortis');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'pulvinar sed nisl nunc');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'in tempus sit amet sem');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'massa quis augue luctus tincidunt');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'turpis enim blandit mi in');
insert into tblnewscategory (category_name, category_description) values ('Family', 'nam ultrices libero non mattis');
insert into tblnewscategory (category_name, category_description) values ('Video', 'est phasellus sit amet');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'in ante vestibulum ante');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'id luctus nec');
insert into tblnewscategory (category_name, category_description) values ('Science', 'penatibus et magnis dis parturient');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'non mi integer ac neque');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'porttitor pede justo eu');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'tortor risus dapibus augue');
insert into tblnewscategory (category_name, category_description) values ('Business', 'in faucibus orci');
insert into tblnewscategory (category_name, category_description) values ('Health', 'justo pellentesque viverra');
insert into tblnewscategory (category_name, category_description) values ('Video', 'amet erat nulla');
insert into tblnewscategory (category_name, category_description) values ('Science', 'neque sapien placerat ante nulla');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'non velit donec diam neque');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'luctus nec molestie sed justo');
insert into tblnewscategory (category_name, category_description) values ('Business', 'consequat varius integer ac');
insert into tblnewscategory (category_name, category_description) values ('Business', 'nisi venenatis tristique');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'donec quis orci eget');
insert into tblnewscategory (category_name, category_description) values ('Technology', 'quis odio consequat');
insert into tblnewscategory (category_name, category_description) values ('Travel', 'nunc proin at turpis');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'et eros vestibulum ac est');
insert into tblnewscategory (category_name, category_description) values ('Family', 'et tempus semper est quam');
insert into tblnewscategory (category_name, category_description) values ('Politics', 'vestibulum ante ipsum primis');
insert into tblnewscategory (category_name, category_description) values ('Health', 'feugiat non pretium');
insert into tblnewscategory (category_name, category_description) values ('Health', 'purus aliquet at feugiat');
insert into tblnewscategory (category_name, category_description) values ('Health', 'sapien varius ut blandit non');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'libero quis orci');
insert into tblnewscategory (category_name, category_description) values ('Family', 'eu est congue');
insert into tblnewscategory (category_name, category_description) values ('Sports', 'penatibus et magnis dis');
insert into tblnewscategory (category_name, category_description) values ('Business', 'interdum in ante vestibulum ante');
insert into tblnewscategory (category_name, category_description) values ('Health', 'curae mauris viverra diam vitae');
insert into tblnewscategory (category_name, category_description) values ('Science', 'lorem ipsum dolor sit');
insert into tblnewscategory (category_name, category_description) values ('Science', 'semper porta volutpat');
insert into tblnewscategory (category_name, category_description) values ('Cars', 'aliquet at feugiat non');
insert into tblnewscategory (category_name, category_description) values ('Video', 'id turpis integer aliquet');
insert into tblnewscategory (category_name, category_description) values ('Religion', 'justo maecenas rhoncus aliquam');
insert into tblnewscategory (category_name, category_description) values ('Video', 'posuere felis sed lacus morbi');
insert into tblnewscategory (category_name, category_description) values ('Sports', 'posuere nonummy integer');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'gravida sem praesent id');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'pulvinar sed nisl nunc rhoncus');
insert into tblnewscategory (category_name, category_description) values ('Family', 'sit amet lobortis sapien');
insert into tblnewscategory (category_name, category_description) values ('Family', 'mi sit amet lobortis');
insert into tblnewscategory (category_name, category_description) values ('World', 'lorem integer tincidunt ante vel');
insert into tblnewscategory (category_name, category_description) values ('Family', 'et tempus semper est quam');
insert into tblnewscategory (category_name, category_description) values ('Entertainment', 'velit eu est');